services:
  - type: web
    name: josh-setterstrom-portfolio
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    domains:
      - joshsetterstrom.ca
